version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: resilienceatlas-frontend
    command: yarn start
    env_file:
      - .env.local
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=UA-123456789-1
      - NEXT_PUBLIC_STATIC_JOURNEYS=true
  # e2e/docker-compose.yml from repo
  # https://github.com/bahmutov/cypress-open-from-docker-compose
  # Cypress container
  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - client
    command: cypress run --headless --browser chrome
    environment:
      # set to 0, to skip layers test
      - CYPRESS_RUN_LAYERS_TESTS=0
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://client:3000
    volumes:
      - ./cypress:/code/cypress/
      - ./cypress-visual-screenshots:/code/cypress-visual-screenshots
      - ./cypress.config.js:/code/cypress.config.js
