version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_HOST=https://www.resilienceatlas.org
    ports:
      - "3000:3000"
    container_name: resilienceatlas-frontend
    command: node server
    env_file: .env
    environment:
      - PORT=3000
      - NODE_ENV=production
  # e2e/docker-compose.yml from repo
  # https://github.com/bahmutov/cypress-open-from-docker-compose
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:12.7.0"
    depends_on:
      - client
    command: cypress run --browser chrome --headless
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://client:3000
    # share the current folder as volume to avoid copying
    working_dir: /test
    volumes:
      - ./cypress:/test/cypress/
      - ./cypress.config.js:/test/cypress.config.js