source 'https://rubygems.org'

ruby '3.2.1'

gem 'capistrano', '~> 3.9'
gem 'capistrano-rbenv', '~> 2.2'
gem 'capistrano-passenger'
gem 'capistrano-yarn'
gem 'capistrano-nvm'
# Please note that without these 2 gems things won't work in the GH Actions
# auto deploy job and all it will ever tell you is "Authentication failed"
gem "bcrypt_pbkdf"
gem "ed25519"
