default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: cigrp

test:
  <<: *default
  database: resilienceatlas_test

staging:
  <<: *default
  database: resilienceatlas_staging

production:
  <<: *default
  database: cigrp
