local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

local_public:
  service: Disk
  root: <%= Rails.root.join("public/storage") %>
  public: true

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID', '') %>
  secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY', '') %>
  bucket: <%= ENV.fetch('S3_BUCKET', 'resilienceatlas') %>
  region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
