version: 0.0
os: linux

files:
  - source: /
    destination: /opt/resilienceatlas
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /opt/resilienceatlas
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStop:
    - location: scripts/codedeploy/application-stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/codedeploy/before-install.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/codedeploy/after-install.sh
      timeout: 1200
      runas: root

  ApplicationStart:
    - location: scripts/codedeploy/application-start.sh
      timeout: 900
      runas: root

  ValidateService:
    - location: scripts/codedeploy/validate-service.sh
      timeout: 300
      runas: ubuntu
