source "https://rubygems.org"

ruby "3.4.4"

gem "rails", "~> 7.2"

gem "terser", "~> 1.2"
gem "slim-rails", "~> 3.6"
gem "dotenv-rails", "~> 3.1"
gem "importmap-rails", "~> 2.1"
gem "shrine", "~> 3.6"
gem "jbuilder", "~> 2.12"
gem "rspec-rails", "~> 7.1"
gem "rswag", "~> 2.15"
gem "image_processing", "~> 1.13"

gem "ed25519", "~> 1.3"
gem "bcrypt_pbkdf", "~> 1.1"

gem "pg", "~> 1.5"
gem "activerecord-postgis-adapter", "~> 10.0"
gem "rgeo", "~> 3.0"
gem "rgeo-geojson", "~> 2.1"
gem "devise", "~> 4.9"
gem "jwt", "~> 2.9"
gem "simple_command", "~> 1.0"
gem "bcrypt", "~> 3.1"
gem "activeadmin", "~> 3.3"
gem "activeadmin_addons", "~> 1.10"
gem "active_model_serializers", "~> 0.10"
gem "active_storage_validations", "~> 1.3"
gem "will_paginate", "~> 4.0"

gem "ffi", "~> 1.17"

gem "cancancan", "~> 3.6"

gem "addressable", "~> 2.8"

gem "rack-cors", "~> 2.0"

# Error tracking and monitoring
gem "rollbar", "~> 3.6"

# Utilities
gem "seed_dump", "~> 3.3"
gem "active_admin_theme", "~> 1.1"
gem "sparkpost_rails", github: "sportstech/sparkpost_rails" # Rails 7 support
gem "rubyzip", "~> 2.4"
gem "prawn", "~> 2.5"
gem "prawn-table", "~> 0.2"
gem "standard", "~> 1.45"
gem "json-schema", "~> 5.1"
gem "ostruct", "~> 0.6"

# Translations
gem "globalize", "~> 7.0"

# Ordering and Tree structure for menus
gem "active_admin-sortable_tree", "~> 2.1"
gem "ancestry", "~> 4.3"
gem "acts_as_list", "~> 1.2"
gem "factory_bot_rails", "~> 6.4"

# Ransack for Active Admin
gem "ransack", "~> 4.3"

group :production, :staging do
  gem "puma", "~> 6.5"
end

group :development, :test do
  gem "byebug", "~> 11.1"
  gem "awesome_print", "~> 1.9"
  gem "faker", "~> 3.5"
end

group :development do
  gem "brakeman", "~> 6.2", require: false
  gem "bundler-audit", "~> 0.9", require: false
  gem "foreman", "~> 0.88"
  gem "better_errors", "~> 2.10"
  gem "binding_of_caller", "~> 1.0"
  gem "annotate", "~> 3.2"
  gem "web-console", "~> 4.2"
  gem "letter_opener_web", "~> 3.0"
end

group :test do
  gem "capybara", "~> 3.40"
  gem "cuprite", "~> 0.15"
  gem "rspec-collection_matchers", "~> 1.2"
  gem "rspec-retry", "~> 0.6"
  gem "super_diff", "~> 0.12"
  gem "rspec-request_snapshot", github: "tsubik/rspec-request_snapshot", branch: "fix/ignore-order"
  gem "rswag-specs", "~> 2.15"
  gem "webmock", "~> 3.24"
  gem "rspec_junit_formatter", "~> 0.6"
end
