# == Schema Information
#
# Table name: source_translations
#
#  id               :bigint           not null, primary key
#  source_id        :bigint           not null
#  locale           :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  reference        :string
#  reference_short  :string
#  license          :string
#

class Source::Translation < Globalize::ActiveRecord::Translation
  # This model is auto-generated by Globalize to support translated attributes
  # for the Source model. We explicitly define it here to ensure proper inheritance.
end