# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "titiler-cogs"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "resilience-atlas-build-artifacts-bucket"
image_repository = "resilience-atlas-pipeline-resources-imagerepository"
region = "us-east-1"
parameter_overrides = "DisableCOG=\"false\" DisableMosaic=\"true\" DisableSTAC=\"true\" LambdaLayerVersion=\"5\""

[default.package.parameters]
s3_bucket = "resilience-atlas-build-artifacts-bucket"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
