AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for titiler-cogs using Python 3.14 (Amazon Linux 2023) with CloudFront CDN'

Parameters:
  FQDN:
    Type: String
    Description: Fully qualified domain name (www.example.com) to use for the Lambda function.
  ZoneId:
    Type: String
    Description: AWS Hosted Zone ID in the format "Z111111QQQQQQQ".
  DisableCOG:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  DisableMosaic:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  DisableSTAC:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  CacheTTL:
    Type: Number
    Default: 86400
    Description: Default cache TTL in seconds (default 24 hours)
  AllowedBuckets:
    Type: String
    Description: Comma-separated list of allowed bucket URIs with provider prefix (e.g., 's3://my-bucket,gs://my-gcs-bucket'). Required - set via TITILER_ALLOWED_BUCKETS GitHub variable.
  RollbarAccessToken:
    Type: String
    Default: ''
    Description: Rollbar access token for error tracking. Optional - set via ROLLBAR_ACCESS_TOKEN GitHub secret.
  RollbarEnvironment:
    Type: String
    Default: 'production'
    Description: Rollbar environment name (e.g., 'production', 'staging').

Resources:
  TitilerCogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Description: 'Titiler: Dynamic tiler'
      MemorySize: 1024
      Timeout: 10
      Events:
        API:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref RestApiGateway
      Environment:
        Variables:
          CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif,.TIF,.tiff
          GDAL_CACHEMAX: 200
          GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
          GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: true
          GDAL_HTTP_MULTIPLEX: true
          GDAL_HTTP_VERSION: 2
          VSI_CACHE: true
          VSI_CACHE_SIZE: 536870912
          CPL_VSIL_CURL_CACHE_SIZE: 200000000
          GDAL_INGESTED_BYTES_AT_OPEN: 32768
          TITILER_API_DISABLE_COG:
            Ref: DisableCOG
          TITILER_API_DISABLE_STAC:
            Ref: DisableSTAC
          TITILER_API_DISABLE_MOSAIC:
            Ref: DisableMosaic
          TITILER_ALLOWED_BUCKETS:
            Ref: AllowedBuckets
          ROLLBAR_ACCESS_TOKEN:
            Ref: RollbarAccessToken
          ROLLBAR_ENVIRONMENT:
            Ref: RollbarEnvironment
      ImageUri: titilercogsfunction:python3.14-v1
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./titiler_cogs
      DockerTag: python3.14-v1

  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - "*/*"
      # Disable API Gateway caching - CloudFront will handle caching
      CacheClusterEnabled: false
      StageName: Prod

  # CloudFront Distribution for global edge caching
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "TiTiler CDN for ${FQDN}"
        Aliases:
          - !Ref FQDN
        HttpVersion: http2and3
        PriceClass: PriceClass_100  # Use only North America and Europe edge locations (cheaper)
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: ApiGatewayOrigin
            DomainName: !Sub "${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: /Prod
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: ApiGatewayOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: !Ref TileCachePolicy
          OriginRequestPolicyId: !Ref TileOriginRequestPolicy
        CacheBehaviors:
          # Health check - no caching
          - PathPattern: /healthz
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled managed policy
            OriginRequestPolicyId: !Ref TileOriginRequestPolicy

  # Custom cache policy for tiles - long TTL
  TileCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-TileCachePolicy"
        Comment: "Cache policy for TiTiler tiles"
        DefaultTTL: !Ref CacheTTL
        MaxTTL: 604800  # 7 days max
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Accept
          QueryStringsConfig:
            QueryStringBehavior: all  # All query params are part of cache key
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

  # Origin request policy - forward necessary headers
  TileOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub "${AWS::StackName}-TileOriginRequestPolicy"
        Comment: "Origin request policy for TiTiler"
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Accept
            - Origin
            - Referer
        QueryStringsConfig:
          QueryStringBehavior: all

  # Certificate for CloudFront (must be in us-east-1)
  CloudFrontCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref FQDN
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref FQDN
          HostedZoneId: !Ref ZoneId

  # Route53 record pointing to CloudFront
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref ZoneId
      Name: !Ref FQDN
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (always this value)

Outputs:
  TitilerCogsApi:
    Description: "API Gateway endpoint URL (internal)"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CloudFrontUrl:
    Description: "CloudFront CDN URL"
    Value: !Sub "https://${FQDN}/"
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID (for cache invalidation)"
    Value: !Ref CloudFrontDistribution
