version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::744899542263:user/resilience-atlas-PipelineUser"
permissions_provider = "AWS IAM"

[staging.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::744899542263:role/resilience-atlas-PipelineExecutionRole"
cloudformation_execution_role = "arn:aws:iam::744899542263:role/resilience-atlas-CloudFormationExecutionRole"
artifacts_bucket = "resilience-atlas-build-artifacts-bucket"
image_repository = "744899542263.dkr.ecr.us-east-1.amazonaws.com/resilience-atlas-pipeline-resources-imagerepository"
region = "us-east-1"

[production.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::744899542263:role/resilience-atlas-PipelineExecutionRole"
cloudformation_execution_role = "arn:aws:iam::744899542263:role/resilience-atlas-CloudFormationExecutionRole"
artifacts_bucket = "resilience-atlas-build-artifacts-bucket"
image_repository = "744899542263.dkr.ecr.us-east-1.amazonaws.com/resilience-atlas-pipeline-resources-imagerepository"
region = "us-east-1"
